/*
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ACLScopeProvider extends org.osate.xtext.aadl2.properties.scoping.PropertiesScopeProvider {

}
