/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL.impl;

import org.eclipse.emf.ecore.EClass;

import org.sireum.aadl.osate.acl.aCL.ACLPackage;
import org.sireum.aadl.osate.acl.aCL.ComputationalModel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Computational Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComputationalModelImpl extends SpecSectionImpl implements ComputationalModel
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComputationalModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ACLPackage.Literals.COMPUTATIONAL_MODEL;
  }

} //ComputationalModelImpl
