/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL.impl;

import org.eclipse.emf.ecore.EClass;

import org.sireum.aadl.osate.acl.aCL.ACLPackage;
import org.sireum.aadl.osate.acl.aCL.Contracts;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Contracts</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ContractsImpl extends SpecSectionImpl implements Contracts
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContractsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ACLPackage.Literals.CONTRACTS;
  }

} //ContractsImpl
