/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL.impl;

import org.eclipse.emf.ecore.EClass;

import org.sireum.aadl.osate.acl.aCL.ACLPackage;
import org.sireum.aadl.osate.acl.aCL.Flows;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Flows</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FlowsImpl extends SpecSectionImpl implements Flows
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FlowsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ACLPackage.Literals.FLOWS;
  }

} //FlowsImpl
