/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.sireum.aadl.osate.acl.aCL.ACLPackage;
import org.sireum.aadl.osate.acl.aCL.SpecSection;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Spec Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SpecSectionImpl extends MinimalEObjectImpl.Container implements SpecSection
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpecSectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ACLPackage.Literals.SPEC_SECTION;
  }

} //SpecSectionImpl
