/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.sireum.aadl.osate.acl.ACLRuntimeModule;
import org.sireum.aadl.osate.acl.ACLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ACLIdeSetup extends ACLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ACLRuntimeModule(), new ACLIdeModule()));
	}
	
}
