/*
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ACLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/sireum/aadl/osate/acl/parser/antlr/internal/InternalACLParser.tokens");
	}
}
