/*
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.sireum.aadl.osate.acl.services.ACLGrammarAccess;

public class ACLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ACLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.sireum.aadl.osate.acl.parser.antlr.internal.InternalACLParser createParser(XtextTokenStream stream) {
		return new org.sireum.aadl.osate.acl.parser.antlr.internal.InternalACLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AnnexSubclause";
	}
	
	public ACLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ACLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
