/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ACLRuntimeModule extends AbstractACLRuntimeModule {
}
