/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ACLStandaloneSetup extends ACLStandaloneSetupGenerated {

	public static void doSetup() {
		new ACLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
