/**
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.ui.contentassist;

import org.sireum.aadl.osate.acl.ui.contentassist.AbstractACLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ACLProposalProvider extends AbstractACLProposalProvider {
}
