/**
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.sireum.aadl.osate.acl.services.ACLGrammarAccess;

@SuppressWarnings("all")
public class ACLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ACLGrammarAccess _aCLGrammarAccess;
  
  protected void _format(final /* AnnexSubclause */Object model, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nGreeting cannot be resolved to a type."
      + "\ngetGreetings cannot be resolved");
  }
  
  public void format(final Object model, final IFormattableDocument document) {
    if (model instanceof XtextResource) {
      _format((XtextResource)model, document);
      return;
    } else if (model instanceof EObject) {
      _format((EObject)model, document);
      return;
    } else if (model == null) {
      _format((Void)null, document);
      return;
    } else if (model != null) {
      _format(model, document);
      return;
    } else if (model != null) {
      _format(model, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(model, document).toString());
    }
  }
}
