/**
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.formatting2;

import com.google.inject.Inject;
import org.eclipse.xtext.xbase.lib.Extension;
import org.osate.xtext.aadl2.properties.formatting2.PropertiesFormatter;
import org.sireum.aadl.osate.acl.services.ACLGrammarAccess;

@SuppressWarnings("all")
public class ACLFormatter extends PropertiesFormatter {
  @Inject
  @Extension
  private ACLGrammarAccess _aCLGrammarAccess;
}
