/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Acl Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sireum.aadl.osate.acl.aCL.AclContract#getSpecs <em>Specs</em>}</li>
 * </ul>
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getAclContract()
 * @model
 * @generated
 */
public interface AclContract extends Contract
{
  /**
   * Returns the value of the '<em><b>Specs</b></em>' containment reference list.
   * The list contents are of type {@link org.sireum.aadl.osate.acl.aCL.SpecSection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specs</em>' containment reference list.
   * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getAclContract_Specs()
   * @model containment="true"
   * @generated
   */
  EList<SpecSection> getSpecs();

} // AclContract
