/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.osate.aadl2.Aadl2Package;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.sireum.aadl.osate.acl.aCL.ACLFactory
 * @model kind="package"
 * @generated
 */
public interface ACLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "aCL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sireum.org/aadl/osate/acl/ACL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "aCL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ACLPackage eINSTANCE = org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.AclSubclauseImpl <em>Acl Subclause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.AclSubclauseImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getAclSubclause()
   * @generated
   */
  int ACL_SUBCLAUSE = 0;

  /**
   * The feature id for the '<em><b>Owned Element</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__OWNED_ELEMENT = Aadl2Package.ANNEX_SUBCLAUSE__OWNED_ELEMENT;

  /**
   * The feature id for the '<em><b>Owned Comment</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__OWNED_COMMENT = Aadl2Package.ANNEX_SUBCLAUSE__OWNED_COMMENT;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__NAME = Aadl2Package.ANNEX_SUBCLAUSE__NAME;

  /**
   * The feature id for the '<em><b>Qualified Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__QUALIFIED_NAME = Aadl2Package.ANNEX_SUBCLAUSE__QUALIFIED_NAME;

  /**
   * The feature id for the '<em><b>Owned Property Association</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__OWNED_PROPERTY_ASSOCIATION = Aadl2Package.ANNEX_SUBCLAUSE__OWNED_PROPERTY_ASSOCIATION;

  /**
   * The feature id for the '<em><b>In Mode</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__IN_MODE = Aadl2Package.ANNEX_SUBCLAUSE__IN_MODE;

  /**
   * The feature id for the '<em><b>Contract</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE__CONTRACT = Aadl2Package.ANNEX_SUBCLAUSE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Acl Subclause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_SUBCLAUSE_FEATURE_COUNT = Aadl2Package.ANNEX_SUBCLAUSE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.ContractImpl <em>Contract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.ContractImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getContract()
   * @generated
   */
  int CONTRACT = 1;

  /**
   * The number of structural features of the '<em>Contract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.SpecSectionImpl <em>Spec Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.SpecSectionImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getSpecSection()
   * @generated
   */
  int SPEC_SECTION = 2;

  /**
   * The number of structural features of the '<em>Spec Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_SECTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.ComputationalModelImpl <em>Computational Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.ComputationalModelImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getComputationalModel()
   * @generated
   */
  int COMPUTATIONAL_MODEL = 3;

  /**
   * The number of structural features of the '<em>Computational Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTATIONAL_MODEL_FEATURE_COUNT = SPEC_SECTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.FlowsImpl <em>Flows</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.FlowsImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getFlows()
   * @generated
   */
  int FLOWS = 4;

  /**
   * The number of structural features of the '<em>Flows</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOWS_FEATURE_COUNT = SPEC_SECTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.ContractsImpl <em>Contracts</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.ContractsImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getContracts()
   * @generated
   */
  int CONTRACTS = 5;

  /**
   * The number of structural features of the '<em>Contracts</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACTS_FEATURE_COUNT = SPEC_SECTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.AclContractImpl <em>Acl Contract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.AclContractImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getAclContract()
   * @generated
   */
  int ACL_CONTRACT = 6;

  /**
   * The feature id for the '<em><b>Specs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_CONTRACT__SPECS = CONTRACT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Acl Contract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACL_CONTRACT_FEATURE_COUNT = CONTRACT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.PeriodicComputationalModelImpl <em>Periodic Computational Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.PeriodicComputationalModelImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getPeriodicComputationalModel()
   * @generated
   */
  int PERIODIC_COMPUTATIONAL_MODEL = 7;

  /**
   * The number of structural features of the '<em>Periodic Computational Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIODIC_COMPUTATIONAL_MODEL_FEATURE_COUNT = COMPUTATIONAL_MODEL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.sireum.aadl.osate.acl.aCL.impl.HyperperiodComputationalModelImpl <em>Hyperperiod Computational Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sireum.aadl.osate.acl.aCL.impl.HyperperiodComputationalModelImpl
   * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getHyperperiodComputationalModel()
   * @generated
   */
  int HYPERPERIOD_COMPUTATIONAL_MODEL = 8;

  /**
   * The feature id for the '<em><b>Relationships</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HYPERPERIOD_COMPUTATIONAL_MODEL__RELATIONSHIPS = COMPUTATIONAL_MODEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Hyperperiod Computational Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HYPERPERIOD_COMPUTATIONAL_MODEL_FEATURE_COUNT = COMPUTATIONAL_MODEL_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.AclSubclause <em>Acl Subclause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Acl Subclause</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.AclSubclause
   * @generated
   */
  EClass getAclSubclause();

  /**
   * Returns the meta object for the containment reference '{@link org.sireum.aadl.osate.acl.aCL.AclSubclause#getContract <em>Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Contract</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.AclSubclause#getContract()
   * @see #getAclSubclause()
   * @generated
   */
  EReference getAclSubclause_Contract();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.Contract <em>Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contract</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.Contract
   * @generated
   */
  EClass getContract();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.SpecSection <em>Spec Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spec Section</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.SpecSection
   * @generated
   */
  EClass getSpecSection();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.ComputationalModel <em>Computational Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Computational Model</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.ComputationalModel
   * @generated
   */
  EClass getComputationalModel();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.Flows <em>Flows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flows</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.Flows
   * @generated
   */
  EClass getFlows();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.Contracts <em>Contracts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contracts</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.Contracts
   * @generated
   */
  EClass getContracts();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.AclContract <em>Acl Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Acl Contract</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.AclContract
   * @generated
   */
  EClass getAclContract();

  /**
   * Returns the meta object for the containment reference list '{@link org.sireum.aadl.osate.acl.aCL.AclContract#getSpecs <em>Specs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Specs</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.AclContract#getSpecs()
   * @see #getAclContract()
   * @generated
   */
  EReference getAclContract_Specs();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.PeriodicComputationalModel <em>Periodic Computational Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Periodic Computational Model</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.PeriodicComputationalModel
   * @generated
   */
  EClass getPeriodicComputationalModel();

  /**
   * Returns the meta object for class '{@link org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel <em>Hyperperiod Computational Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hyperperiod Computational Model</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel
   * @generated
   */
  EClass getHyperperiodComputationalModel();

  /**
   * Returns the meta object for the attribute '{@link org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel#getRelationships <em>Relationships</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Relationships</em>'.
   * @see org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel#getRelationships()
   * @see #getHyperperiodComputationalModel()
   * @generated
   */
  EAttribute getHyperperiodComputationalModel_Relationships();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ACLFactory getACLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.AclSubclauseImpl <em>Acl Subclause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.AclSubclauseImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getAclSubclause()
     * @generated
     */
    EClass ACL_SUBCLAUSE = eINSTANCE.getAclSubclause();

    /**
     * The meta object literal for the '<em><b>Contract</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACL_SUBCLAUSE__CONTRACT = eINSTANCE.getAclSubclause_Contract();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.ContractImpl <em>Contract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.ContractImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getContract()
     * @generated
     */
    EClass CONTRACT = eINSTANCE.getContract();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.SpecSectionImpl <em>Spec Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.SpecSectionImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getSpecSection()
     * @generated
     */
    EClass SPEC_SECTION = eINSTANCE.getSpecSection();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.ComputationalModelImpl <em>Computational Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.ComputationalModelImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getComputationalModel()
     * @generated
     */
    EClass COMPUTATIONAL_MODEL = eINSTANCE.getComputationalModel();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.FlowsImpl <em>Flows</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.FlowsImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getFlows()
     * @generated
     */
    EClass FLOWS = eINSTANCE.getFlows();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.ContractsImpl <em>Contracts</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.ContractsImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getContracts()
     * @generated
     */
    EClass CONTRACTS = eINSTANCE.getContracts();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.AclContractImpl <em>Acl Contract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.AclContractImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getAclContract()
     * @generated
     */
    EClass ACL_CONTRACT = eINSTANCE.getAclContract();

    /**
     * The meta object literal for the '<em><b>Specs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACL_CONTRACT__SPECS = eINSTANCE.getAclContract_Specs();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.PeriodicComputationalModelImpl <em>Periodic Computational Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.PeriodicComputationalModelImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getPeriodicComputationalModel()
     * @generated
     */
    EClass PERIODIC_COMPUTATIONAL_MODEL = eINSTANCE.getPeriodicComputationalModel();

    /**
     * The meta object literal for the '{@link org.sireum.aadl.osate.acl.aCL.impl.HyperperiodComputationalModelImpl <em>Hyperperiod Computational Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sireum.aadl.osate.acl.aCL.impl.HyperperiodComputationalModelImpl
     * @see org.sireum.aadl.osate.acl.aCL.impl.ACLPackageImpl#getHyperperiodComputationalModel()
     * @generated
     */
    EClass HYPERPERIOD_COMPUTATIONAL_MODEL = eINSTANCE.getHyperperiodComputationalModel();

    /**
     * The meta object literal for the '<em><b>Relationships</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HYPERPERIOD_COMPUTATIONAL_MODEL__RELATIONSHIPS = eINSTANCE.getHyperperiodComputationalModel_Relationships();

  }

} //ACLPackage
