/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
} // Expr
