/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flows</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getFlows()
 * @model
 * @generated
 */
public interface Flows extends SpecSection
{
} // Flows
