/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hyperperiod Computational Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel#getRelationships <em>Relationships</em>}</li>
 * </ul>
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getHyperperiodComputationalModel()
 * @model
 * @generated
 */
public interface HyperperiodComputationalModel extends ComputationalModel
{
  /**
   * Returns the value of the '<em><b>Relationships</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationships</em>' attribute.
   * @see #setRelationships(String)
   * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getHyperperiodComputationalModel_Relationships()
   * @model
   * @generated
   */
  String getRelationships();

  /**
   * Sets the value of the '{@link org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel#getRelationships <em>Relationships</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationships</em>' attribute.
   * @see #getRelationships()
   * @generated
   */
  void setRelationships(String value);

} // HyperperiodComputationalModel
