/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;

import org.eclipse.emf.common.util.EList;

import org.osate.aadl2.NamedElement;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hyperperiod Computational Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sireum.aadl.osate.acl.aCL.HyperperiodComputationalModel#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getHyperperiodComputationalModel()
 * @model
 * @generated
 */
public interface HyperperiodComputationalModel extends ComputationalModel
{
  /**
   * Returns the value of the '<em><b>Constraints</b></em>' reference list.
   * The list contents are of type {@link org.osate.aadl2.NamedElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' reference list.
   * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getHyperperiodComputationalModel_Constraints()
   * @model
   * @generated
   */
  EList<NamedElement> getConstraints();

} // HyperperiodComputationalModel
