/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Periodic Computational Model</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getPeriodicComputationalModel()
 * @model
 * @generated
 */
public interface PeriodicComputationalModel extends ComputationalModel
{
} // PeriodicComputationalModel
