/**
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.aCL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Spec Section</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sireum.aadl.osate.acl.aCL.ACLPackage#getSpecSection()
 * @model
 * @generated
 */
public interface SpecSection extends EObject
{
} // SpecSection
