/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.acl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ACLUiModule extends AbstractACLUiModule {

	public ACLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
