/*
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.sireum.aadl.osate.acl.ui.internal.ACLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ACLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ACLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ACLActivator.getInstance().getInjector(ACLActivator.ORG_SIREUM_AADL_OSATE_ACL_ACL);
	}
	
}
