/*
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ACLProposalProvider extends org.sireum.aadl.osate.acl.ui.contentassist.AbstractACLProposalProvider {

}
