/*
 * generated by Xtext
 */
package org.sireum.aadl.osate.acl.ui.contentassist

import org.sireum.aadl.osate.acl.ui.contentassist.AbstractACLProposalProvider
import com.google.inject.Inject
import org.sireum.aadl.osate.acl.services.ACLGrammarAccess

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class ACLProposalProvider extends AbstractACLProposalProvider {
	@Inject extension ACLGrammarAccess
}
